### ISSUE TITLE
No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar) 

### ISSUE THREAD

**Issue by this-sunil** [codenameakshay/async_wallpaper#10]
File /data/user/0/com.example.*/cache/libCachedImageData/228ca370-1c5a-11ed-b883-0be05e0c521a.mp4
I/Arguments (10269): configureFlutterEngine: /data/user/0/com.example.wallpaper_app/cache/libCachedImageData/228ca370-1c5a-11ed-b883-0be05e0c521a.mp4
E/AndroidRuntime(10269): FATAL EXCEPTION: main
E/AndroidRuntime(10269): Process: com.example.wallpaper_app, PID: 10269
E/AndroidRuntime(10269): java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
E/AndroidRuntime(10269): 	at com.codenameakshay.async_wallpaper.AsyncWallpaperPlugin.onMethodCall(AsyncWallpaperPlugin.java:234)
E/AndroidRuntime(10269): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(10269): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(10269): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(10269): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime(10269): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(10269): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10269): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(10269): 	at android.app.ActivityThread.main(ActivityThread.java:6138)
E/AndroidRuntime(10269): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10269): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/AndroidRuntime(10269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
I/Process (10269): Sending signal. PID: 10269 SIG: 9
Lost connection to device.

**Comment by this-sunil** [comment]
for set live wallpaper

**Comment by codenameakshay** [comment]
Thanks for the stack trace. PR #62 removes the Android code path that called Java NIO `File.toPath()`. Video and file inputs are now copied and validated using Android-compatible bounded streams before wallpaper setup, so this should work on the plugin's supported Android versions.

Please test the 3.2.0 branch with the same MP4 and device:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please report the Android version, source type/path, returned operation result, and a new crash log if `NoSuchMethodError: File.toPath()` still occurs.

**Comment by codenameakshay** [comment]
Fixed. The plugin no longer calls `File.toPath()` anywhere — `rg "toPath\(" android/ lib/ ios/` returns nothing. Sources are opened with bounded streams (`WallpaperSourceLoader`, `BoundedSourceOpener`), which is also API 24-safe. The 3.0 Kotlin migration removed the original call site.
