### ISSUE TITLE
Invoking setWallpaper inside workmanager yields PlaformException

### ISSUE THREAD

**Issue by innomatica** [codenameakshay/async_wallpaper#15]
I want to change the wallpaper in the background at a certain point. WorkManager invokes
```
AsyncWallpaper.setWallpaperFromFile(localFilePath);
```
and creates following PlatformException
```
E/MethodChannel#async_wallpaper(14385): Failed to handle method call
E/MethodChannel#async_wallpaper(14385): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startActivity(android.content.Intent)' on a null object reference
E/MethodChannel#async_wallpaper(14385): 	at com.codenameakshay.async_wallpaper.AsyncWallpaperPlugin.home(AsyncWallpaperPlugin.java:158)
E/MethodChannel#async_wallpaper(14385): 	at com.codenameakshay.async_wallpaper.AsyncWallpaperPlugin.onMethodCall(AsyncWallpaperPlugin.java:210)
E/MethodChannel#async_wallpaper(14385): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#async_wallpaper(14385): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#async_wallpaper(14385): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#async_wallpaper(14385): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#async_wallpaper(14385): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#async_wallpaper(14385): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#async_wallpaper(14385): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#async_wallpaper(14385): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#async_wallpaper(14385): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#async_wallpaper(14385): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#async_wallpaper(14385): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#async_wallpaper(14385): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Any suggestion would be appreciated.

TIA,

**Flutter:**
 - version: 3.3.9
 - channel: stable

**Dart:**
 - version: 2.18.5

**Comment by jjfster** [comment]
Did you ever get this working?

**Comment by innomatica** [comment]
No I didn't.

**Comment by codenameakshay** [comment]
PR #62 fixes the Activity-related background failure for direct static wallpapers. The direct apply engine is Activity-independent, so it can run from WorkManager; UI-dependent operations such as the cropper, picker, video preview, and OpenGL preview now return `foregroundRequired` instead of crashing when no Activity exists.

For example, use a direct `StaticWallpaperRequest` with `WallpaperSource.filePath(...)` and `WallpaperApplyStrategy.direct`.

Please test the 3.2.0 branch from the same worker:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please share the request type, WorkManager execution context, and complete structured result. If it still fails, include the new exception and Android version.

**Comment by codenameakshay** [comment]
Fixed. Direct static application is now fully headless and never touches an Activity: `StaticWallpaperEngine.applyDirect` has no Activity dependency, and the system-UI strategies return `WallpaperOperationStatus.foregroundRequired` instead of throwing the old NullPointerException when no Activity is attached.

Use `WallpaperApplyStrategy.direct` from a worker:

```dart
await AsyncWallpaper.applyWallpaper(StaticWallpaperRequest(
  source: WallpaperSource.filePath(path),
  target: WallpaperTarget.home,
  strategy: WallpaperApplyStrategy.direct,
));
```

Do not call the cropper/picker/live-wallpaper preview from a worker — those need a foreground user flow.
